config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:sessions]
  as :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root 'users#index'

  resources :users
  get '/equipment' => 'equipment#index'
  get '/roster' => 'users#index'
  get '/users' => 'users#index'
  get '/users/:id/positions' => 'users#positions'
  patch '/users/assign_position/:id' => 'users#assign_position'
  get '/users/:id/waiver' => 'users#waiver'
  get '/users/:id/dues' => 'users#dues'
  post '/users/:id/edit' => 'users#edit'
  patch '/users/update/:id' => 'users#update'
  post '/users/delete/:id' => 'users#destroy'
  get '/notifications' => 'notifications#index'
  resources :equipment
  post '/equipment/new' => 'equipment#new'
  post '/equipment/:id/edit' => 'equipment#edit'
  post '/equipment/delete/:id' => 'equipment#destroy'
  patch '/equipment/update/:id' => 'equipment#update'
  post '/equipment/eqrequest/:id' => 'equipment#eqrequest'
  post '/equipment/eqreturn/:id' => 'equipment#eqreturn'
  post '/equipment/eqrepair/:id' => 'equipment#eqrepair'
  post '/equipment/canceleqrequest/:id' => 'equipment#canceleqrequest'
  post '/notifications/approve/:id' => 'notifications#approve'
  post '/notifications/deny/:id' => 'notifications#deny'

end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
end

app/models/equipment_type.rb
class EquipmentType < ActiveRecord::Base
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  respond_to :html, :json
  def index
    @equipment = Equipment.where("users_id IS NULL").joins("join (select id, status_desc from statuses) s on s.id=equipment.status_id", "join (select id, description as type from equipment_types) et on et.id=equipment.equipment_type_id").
		 select("equipment.*, status_desc, type") 
    @curr_user = current_user.id
    @borrowed_eq = Equipment.where("#{@position.include?("armorer") ? "users_id IS NOT NULL" : "users_id = #{@curr_user}"}").joins("join (select id, status_desc from statuses) s on s.id=equipment.status_id", "join (select id, description as type from equipment_types) et on et.id=equipment.equipment_type_id").
		  select("equipment.*, status_desc, type")
#     @requested_eq = EquipmentRequest.where("users_id == #{@curr_user}").joins("join (select id as 'requestid' from request_statuses where status_desc like 'Pending') rs on rs.id=request_status_id", "join(select request_type_description, id from request_types) as rt on rt.id=request_types_id").select("id")[0][:id]}) as si on si.requestid=checkout_table.request_status_id").select("checkout_table.*")
    #{RequestType.where("request_type_description like 'Repair'")
    @requested_eq = EquipmentRequest.where("users_id == #{@curr_user} and  request_types_id!=#{RequestType.where("request_type_description like 'Repair'").select("id")[0][:id]}")
				    .joins("join (select id from request_statuses where status_desc like 'Pending') rs on rs.id=request_status_id", 
                                           "join(select request_type_description, id from request_types) as rt on rt.id=request_types_id")
				    .select("checkout_table.*, rt.request_type_description as rt_desc")
  end
  
  def new
    @new_item=Equipment.new
    respond_modal_with @new_item
  end
  
  def create
    @new_item = Equipment.new(inventory_params)
    #@new_item.status=1
    #respond_modal_with @new_item, location: "/equipment"
    authorize @new_item, :general_add_eq?
    respond_to do |format|
      if @new_item.save
	#flash[:success] = "#{@new_item.description} added to inventory"
        format.html { redirect_to '/equipment', :flash => { :success => "'#{@new_item.description}' added to inventory."} }
	format.html {redirect_to '/equipment'}
        format.json { render action: 'show', status: :created, location: '/equipment' }
        # added:
        format.js   { render action: 'show', status: :created, location: '/equipment' }
      else
        format.html { render action: 'new' }
        format.json { render json: @new_item.errors, status: :unprocessable_entity }
        # added:
        format.js   { render json: @new_item.errors, status: :unprocessable_entity }
      end
    end
  end
    
    def edit
     @current_item = Equipment.find(params[:id])
     respond_modal_with @current_item
  end
  
  def update
     @current_item = Equipment.find(params[:id])
     authorize @current_item, :armorer?
     @current_item.update(inventory_params)
     respond_to do |format|
	  format.html {redirect_to '/equipment', :flash => { :success => "'#{@current_item.description}' updated."}}
	  format.json {head :ok}
      end
  end
  
  def destroy
      @remove_item = Equipment.find(params[:id])
      authorize @remove_item, :armorer?
      @remove_item.destroy
      
      respond_to do |format|
	  format.html {redirect_to '/equipment', :flash => { :error => "'#{@remove_item.description}' deleted."}}
	  format.json {head :ok}
      end
  end
  
  def eqrequest
    current_item = Equipment.find(params[:id])
    authorize current_item
    @curr_user = current_user.id
    cust_params = Hash.new
    cust_params[:equipment_id] = current_item.id
    cust_params[:users_id] = @curr_user
    cust_params[:time_opened] = Time.now
    cust_params[:request_status_id] = RequestStatus.where("status_desc like 'Pending'").select("id")[0][:id]
    cust_params[:request_types_id] = RequestType.where("request_type_description like 'Checkout'").select("id")[0][:id]
    new_request = EquipmentRequest.new(cust_params)
    new_request.save
#     notif_params = Hash.new
#     notif_params[:from_user_id] = @curr_user
#     notif_params[:timestamp] = cust_params[:time_requested]
#     notif_params[:message] = "#{@curr_user} has requested #{@current_item.description}"
#     notif_params[:viewed] = false
#     temp= Position.where("title like 'armorer'").select("users_id")
#     puts "armorer id is #{temp.collect{|u| u.users_id}}"
#     notif_params[:to_user_id] = temp.collect{|u| u.users_id}[0]
#     @new_notification = Notification.new(notif_params)
#     @new_notification.save
    
    respond_to do |format|
	  format.html {redirect_to '/equipment', :flash => { :success => "'#{current_item.description}' has been requested."}}
	  format.json {head :ok}
      end
  end
  
  def eqreturn
      current_item = Equipment.find(params[:id])
      @curr_user = current_user.id
      cust_params = Hash.new
      cust_params[:equipment_id] = current_item.id
      cust_params[:users_id] = @curr_user
      cust_params[:time_opened] = Time.now
      cust_params[:request_status_id] = RequestStatus.where("status_desc like 'Pending'").select("id")[0][:id]
      cust_params[:request_types_id] = RequestType.where("request_type_description like 'Return'").select("id")[0][:id]
      new_request = EquipmentRequest.new(cust_params)
      new_request.save
    respond_to do |format|
	  format.html {redirect_to '/equipment', :flash => { :success => "'#{current_item.description}' has been marked as returned.  Pending verification."}}
	  format.json {head :ok}
      end
  end
  
  def canceleqrequest
    current_item = Equipment.find(params[:id])
    @curr_user = current_user.id
    current_request = EquipmentRequest.find(EquipmentRequest.where("equipment_id = #{current_item.id} and users_id = #{@curr_user} and time_closed is null").select("id")[0][:id])
    cust_params = Hash.new
    cust_params[:request_status_id] = RequestStatus.where("status_desc like 'Withdrawn'").select("id")[0][:id]
    cust_params[:time_closed] = Time.now
    puts cust_params
    current_request.update(cust_params)
    
    respond_to do |format|
	  format.html {redirect_to '/equipment', :flash => { :success => "'#{current_item.description}' request has been withdrawn."}}
	  format.json {head :ok}
      end
  end
  
  def eqrepair
    current_item = Equipment.find(params[:id])
    @curr_user = current_user.id
    cust_params = Hash.new
    cust_params[:equipment_id] = current_item.id
    cust_params[:users_id] = @curr_user
    cust_params[:time_opened] = Time.now
    cust_params[:request_status_id] = RequestStatus.where("status_desc like 'Pending'").select("id")[0][:id]
    cust_params[:request_types_id] = RequestType.where("request_type_description like 'Repair'").select("id")[0][:id]
    new_request = EquipmentRequest.new(cust_params)
    new_request.save
    respond_to do |format|
	  format.html {redirect_to '/equipment', :flash => { :success => "'#{current_item.description}' has been marked as needing repair.  Pending verification."}}
	  format.json {head :ok}
      end
  end

  private

  def inventory_params
    #params.require(:equipment).permit(:typeid, :itemname, :description)
    params.require(:equipment).permit(:status_id, :description, :equipment_type_id, :parts)
  end
  
  def user_not_authorized(exception)
    policy_name = exception.policy.class.to_s.underscore
    puts policy_name
    if policy_name="eqrequest?"
      respond_to do |format|
	  format.html {redirect_to '/equipment', :flash => { :error => "You must have a completed waiver and dues to check out equipment"}}
	  format.json {head :ok}
      end
    else
      respond_to do |format|
	  format.html {redirect_to '/equipment', :flash => { :error => "You are not authorized to perform this action."}}
	  format.json {head :ok}
      end
    end
  end
end

app/views/equipment/_edit_item.html.erb
<%= form_for @current_item, :url => "/equipment/update/#{@current_item.id}" do |f| %>
  <% if @current_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@current_item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @current_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% content_for :header do %>
    <h4 class="modal-title" id="myModalLabel">'<%= @current_item.description %>'</h4>
  <% end %>
  <div class="input-reskin">
  <%#= f.label :description, 'Description:' %>
  <%#= f.text_field :description%>
  <%= f.label :Type, 'Equipment Type:'%>
  <%= EquipmentType.find(@current_item.equipment_type_id).description.capitalize %></br></br>
  <%= f.label :parts, 'Parts' %>
  <%= f.text_field :parts %>
  <%#= f.label :equipment_type_id, 'Equipment Type:' %>
  <%#= f.text_field :equipment %>
  <%= f.label :status_id, 'Status:' %>
  <% if @position.include?("armorer") %>
  <%= f.collection_select(:status_id, Status.all, :id, :status_desc.to_s)%></br>
  <% else %>
  <%= f.collection_select(:status_id, Status.where("status_desc like 'Ordered'"), :id, :status_desc.to_s)%></br>
  <% end %>
  </div>
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    
    <%= f.submit 'Save', class: 'btn btn-success' do%>
<% end %>

app/views/equipment/_form.html.erb
<%= form_for(@new_item) do |f| %>
  <% if @new_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@new_item.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @new_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% content_for :header do %>
    <h4 class="modal-title" id="myModalLabel">New Item</h4>
  <% end %>
  <div class="input-reskin">
  <%= f.label :description, 'Description:' %>
  <%= f.text_field :description%></br>
  <%= f.label :equipment_type_id, 'Equipment Type:' %>
  <%= f.collection_select(:equipment_type_id, EquipmentType.all, :id, :description.to_s)%></br>
  <%= f.label :status_id, 'Status:' %>
  <% if @position.include?("armorer") %>
  <%= f.collection_select(:status_id, Status.all, :id, :status_desc.to_s)%></br>
  <% else %>
  <%= f.collection_select(:status_id, Status.where("status_desc like 'Ordered'"), :id, :status_desc.to_s)%></br>
  <% end %>
  </div>
    
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <%= f.submit 'Save', class: 'btn btn-success'%>
<% end %>

app/views/equipment/edit.html.erb
<%= render 'edit_item' %>

app/views/equipment/index.html.erb
<html><body>
<div class="conatainer">
    <div class="Absolute-Center is-Responsive text-centered">
	<div class="overflow-auto" style="overflow: auto; height: 98%;">
	<table class="table table-bordered table-striped">
	  <th>Equipment Description</th>
	  <th>Type</th>
	  <% if @position.size > 0 %>
	    <th>Parts</th>
	  <% end %>
	  <th>Status</th>
	  <th colspan="2" style="text-align: center">Actions</th>
	  <% @equipment.each do |item| %>
	    <tr>
		<td><%= item.description %></td>
		<td><%= item.type %></td>
		<% if @position.size>0 %>
		  <td><%= item.parts %></td>
		<% end %>
		<td><%= item.status_desc %></td>
		<% if @position.include?("armorer") %>
		  <td><%= link_to "/equipment/#{item.id}/edit", data: { modal: true}, :class=>'btn btn-info' do%><i class="fa fa-file-text-o">&nbspEdit</i><% end %>
</td>
		  <td><%= link_to "/equipment/delete/#{item.id}", :confirm=> 'Do you really want to delete this item?', :method=>:destroy, :class=>'btn btn-danger' do%><i class="fa fa-trash-o fa-sm"><%= " Delete" %></i><% end %><td>
		<% end %>
		<% if !@position.include?("armorer") %>
		  <% if !@borrowed_eq.to_a.collect{|eq| eq["id"]}.include?(item.id) %>
		  <% if item.status_desc!="Not Working" %>
		    <% if !@requested_eq.to_a.collect{|eqr| eqr["equipment_id"]}.include?(item.id) %>
			<td style="text-align: center"><%= link_to 'Request', "/equipment/eqrequest/#{item.id}", :confirm=> 'Are you certain you want to request to borrow this item?', :method=>:eqrequest, :class=>'btn btn-success' %></td>
		    <% else %>
			<td style="text-align: center"><%= link_to 'Cancel Request', "equipment/canceleqrequest/#{item.id}", :confirm=> 'Are you certain you want to cancel your request?', :method=>:canceleqrequest, :class=>'btn btn-warning' %></td>
		    <% end %>
		  <% end %>
		  <% else %>
		    
		  <% end %>
		  <% if item.status_desc!="Not Working" %>
		    <td style="text-align: center"><%= link_to 'Repair', "equipment/eqrepair/#{item.id}", :confirm=>'Are you certain this equipment is in need of repair?', :method=>:eqrepair, :class=>'btn btn-small' %></td>
		  <% end %>
		<% end %>
	    </tr>
	  <% end %>
	</table>
	</div>
    </div>
  <% if @position.include?("armorer") or @position.include?("treasurer") or @position.include?("president") %>
    <div style="float: right;"><%= link_to equipment_new_path, data: { modal: true }, :class=>'btn btn-success' do %><i class="fa fa-plus-square-o"><%= " Add Equipment" %></i><% end %></div>
  <% end %>
  
  <% if @borrowed_eq.size>0 %>
  </br></br>
  <b>Borrowed Equipment</b>
  <div class="Absolute-Center is-Responsive text-centered">
	<div class="overflow-auto" style="overflow: auto; height: 98%;">
	<table class="table table-bordered table-striped">
	  <th>Equipment ID</th>
	  <th>Equipment Description</th>
	  <th>Type</th>
	  <th>Status</th>
	  <% if @position.include?("armorer") %>
	    <th>Borrower</th>
	  <% else %>
	    <th style="text-align: center">Actions</th>
	  <% end %>
	  <% @borrowed_eq.each do |item| %>
	    <tr>
		<td><%= item.id %></td>
		<td><%= item.description %></td>
		<td><%= item.type %></td>
		<td><%= item.status_desc %></td>
		<% if @position.include?("armorer") %>
		  <td><%= item.users_id %></td>
		<% else %>
		    <% if !@requested_eq.to_a.collect{|eqr| eqr["equipment_id"]}.include?(item.id) %>
		      <td style="text-align: center"><%= link_to 'Return', "/equipment/eqreturn/#{item.id}", :confirm=> 'Are you certain youre ready to return this equipment?', :method=>:eqreturn, :class=>'btn btn-info' %> </td>
		    <% else %>
			<td style="text-align: center"><%= link_to "equipment/canceleqrequest/#{item.id}", :confirm=> 'Are you certain you want to cancel your request?', :method=>:canceleqrequest, :class=>'btn btn-warning' do %><i class="fa fa-ban"><%= " Cancel Return"%><% end %></i></td>
		    <% end %>
		<% end %>
	    </tr>
	  <% end %>
	</table>
	</div>
    </div>
  <% end %>
  </div>
  </div>
</body></html>

app/views/equipment/new.html.erb
<%= render 'form' %>

app/views/equipment/show.html.erb
<div style="float: right;"><%= link_to 'Modal Test', new_inventory_item_path, data: { modal: true }, :class=>'btn btn-success' %></div>
	